# Generated by Django 4.2.8 on 2023-12-13 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[(1, '云计算'), (2, 'Python全栈'), (3, 'Go开发')], max_length=32, verbose_name='分类')),
                ('image', models.CharField(max_length=255, verbose_name='封面')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('summary', models.CharField(max_length=255, verbose_name='简介')),
                ('text', models.TextField(verbose_name='博文')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='评论数')),
                ('favor_count', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('token', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='token')),
            ],
        ),
        migrations.CreateModel(
            name='Favor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='博客')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.userinfo', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150, verbose_name='评论内容')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='博客')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.userinfo', verbose_name='用户')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.userinfo', verbose_name='创建者'),
        ),
        migrations.AddConstraint(
            model_name='favor',
            constraint=models.UniqueConstraint(fields=('blog', 'user'), name='unique_favor_blog_user'),
        ),
    ]
